#########################
 ## Sample Sass Lint File
 #########################
 # Linter Options
 options:
   # Don't merge default rules
   merge-default-rules: false
   # Set the formatter to 'html'
   #formatter: html
   # Output file instead of logging results
   #output-file: 'linters/sass-lint.html'
 # File Options
 files:
   include: 'css/**/*.s+(a|c)ss'
   ignore:
     - 'node_modules/**/*.*'
     - 'bower_components/**/*.*'
 # Rule Configuration
 rules:
   extends-before-mixins: 2
   extends-before-declarations: 2
   placeholder-in-extend: 2
   mixins-before-declarations:
     - 2
     - exclude:
         - breakpoint
         - mq
   no-warn: 2
   no-debug: 2
   no-ids: 2
   no-important: 0
   no-duplicate-properties: 2
   no-empty-rulesets: 0
   no-vendor-prefixes: 0
   hex-notation:
     - 2
     - style: uppercase
   indentation:
     - 2
     - size: 2
   property-sort-order:
     - 0
     - order:
         - display
         - margin
       ignore-custom-properties: true
   variable-for-property:
     - 2
     - properties:
         - content
   final-newline: 2
